### ISSUE TITLE
ModuleNotFoundError: No module named 'settings'

### ISSUE THREAD

**Issue by Mobin-khorushi** [SanjoSolutions/sims4-mod-development-tools#1]
![image](https://github.com/SanjoSolutions/sims4-mod-development-tools/assets/63199334/4934fdd5-44f4-4302-8035-34fe47c30996)

i followed all your steps shared at 

https://medium.com/swlh/the-sims-4-modern-python-modding-part-5-project-template-c9ffee48ab4e
and
https://medium.com/@junebug12851/the-sims-4-modern-python-modding-part-1-setup-83d1a100c5f6

but when I want to run the devmod.py I get this errors ! what I missed ?

**Comment by Mobin-khorushi** [comment]
sorry for my silly issue by the way you changes settings.py to settings_global.py also not included project_name as sample in settings_global.py that was the issue anyway lets keep it here for future if anyone had this problem too

**Comment by SanjoSolutions** [comment]
Fixed with https://github.com/SanjoSolutions/sims4-mod-development-tools/commit/4ce944ac31c8fa0d73d83b0cace17e9e0333b678.
See step 1 in the [documentation](https://github.com/SanjoSolutions/sims4-mod-development-tools?tab=readme-ov-file#setting-up-the-sims-4-mod-development-tools-for-a-project) for how it's done with the latest version.

@Mobin-khorushi Thanks for reporting it.
